hostname: docker

rancher: 
  network:
    interfaces:
      eth0:
	address: 192.168.1.252/24
	gateway: 192.168.1.1
	mtu: 1500
	dhcp: false
    dns:
      nameservers:
      - 1.1.1.1
      - 1.0.0.1

ssh_authorized_keys:
  - ssh-rsa 0XY8o3kqf4aBtyE7LqPKWGNQdFazIvxe1zo8H4gTYwM administrator@WIN-H21LKB04LSA
  - 
